### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected extension byte (at offset 1)

### ISSUE THREAD

**Issue by zhukeev** [CodingAleCR/http_interceptor#113] opened 2022-05-12 12:16 UTC
**Describe the bug**
Can't send encoded body with `GZipCodec().encode(utf8.encode(
        json.encode(body),
      ))`
but http can
**To Reproduce**
1. Encode body with `GZipCodec().encode(utf8.encode( json.encode(body),))`
2. Make post request

**Expected behavior**

**Screenshots**

**Please complete the following information):**
 - Flutter version:  2.10.4
 - IDE: VS Code
 - `http_interceptor: ^2.0.0-beta.5`

**Additional context**

**Comment by CodingAleCR** [comment] 2022-08-03 05:57
Hey @zhukeev this seems to be an exception coming straight from the SDK, not a problem from the library. In any case, digging a bit online I found [this SO thread](https://stackoverflow.com/questions/39735145/how-to-compress-a-string-using-gzip-or-similar-in-dart) that might help you solve your issues. 

As a bonus, I've added a test for checking GZip compression in #114 . This test takes the approach recommended in the thread I just linked and worked like a charm for fixing the exception you were having (from what I could reproduce).

As this is not exactly the library's fault, I'll close the issue and pin it for others in the future.

**Closed by CodingAleCR** 2022-08-03 05:57 UTC
Labels: bug
